version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    allowed_updates:
      - match:
          update_type: 'all'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
      - match:
          dependency_type: 'production'
          update_type: 'semver:minor'
    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true
